version: "3"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - site_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - site_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  site_mysql:
networks:
  site_network:
    driver: bridge
